### ISSUE TITLE
Page Rendering Issue

### ISSUE THREAD

**Issue by gilbertk422** [marcelovicentegc/django-react-typescript#8]
I cloned project and followed all steps to run locally and it works well except template engine codes on index.html and didn't render correctly.

![image](https://user-images.githubusercontent.com/62311404/116178386-dbcb6f00-a6eb-11eb-9df0-03cef75d4605.png)

As you can see here, I see {% load static %} and missing resources which is loaded in template engine.

@marcelovicentegc could you figure this out? Thanks

**Comment by marcelovicentegc** [comment]
Hi, @cesarrdz116! I'll take a look into that. Just FYI, once you run this in production the `{% load static %}` tag goes away because that template will be rendered by Django's template engine. You see this tag now because on dev mode React renders the page, and it doesn't know what to do with Django's template tags.

I have a solution on the back of my head and will work on that 😉 . Thanks, @cesarrdz116!

**Comment by marcelovicentegc** [comment]
Hi there @gilbertk422 :wave: ! just to let you know that I'm revisiting this project and I've got rid of this template engine code while upgrading Django and React :wink:
